#!/bin/bash

RED='\033[0;31m'
YELLOW='\033[1;33m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color

sudo pacman -Syu --noconfirm wget vim

#### Dual boot ####
read -p "$(echo -e ${WHITE}"Configure dualboot? (y,n) ${NC}")" DUAL
if [[ $DUAL == "Y" || $DUAL == "y" ]]; then
    sudo pacman -S --noconfirm grub efibootmgr dosfstools mtools os-prober
    sudo grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
    sudo grub-mkconfig -o /boot/grub/grub.cfg
    sudo sed -i 's/#GRUB_DISABLE_OS_PROBER=false/GRUB_DISABLE_OS_PROBER=false/g' /etc/default/grub
    sudo grub-mkconfig -o /boot/grub/grub.cfg
fi

read -p "$(echo -e ${WHITE}"Configure nvidia drivers? (y,n) ${NC}")" NVIDIA
# see https://github.com/korvahannu/arch-nvidia-drivers-installation-guide?tab=readme-ov-file
if [[ $NVIDIA == "Y" || $NVIDIA == "y" ]]; then
    sudo pacman -S nvidia-dkms nvidia-dkms-utils linux-headers qt6-wayland qt6ct libva
    #Additionally libva-nvidia-driver-git (AUR) to fix crashes in some Electron-based applications, such as Unity Hub.
    
    sudo sed -i '/^GRUB_CMDLINE_LINUX_DEFAULT=".*/ s/.$//' /etc/default/grub
    sudo sed -i '/^GRUB_CMDLINE_LINUX_DEFAULT=".*/ s/$/ nvidia-drm.modeset=1"/' /etc/default/grub
    sudo grub-mkconfig -o /boot/grub/grub.cfg
    
    sudo sed -i '/^MODULES=(.*/ s/.$//' /etc/mkinitcpio.conf
    sudo sed -i '/^MODULES=(.*/ s/$/ nvidia nvidia_modeset nvidia_uvm nvidia_drm)/' /etc/mkinitcpio.conf
    sudo sed -i '/^HOOKS=(.*kms.*/ s/kms//' /etc/mkinitcpio.conf
    sudo mkinitcpio --config /etc/mkinitcpio.conf --generate /boot/initramfs-custom.img

    sudo echo "options nvidia-drm modeset=1" >> /etc/modprobe.d/nvidia.conf
    
    #wget https://raw.githubusercontent.com/korvahannu/arch-nvidia-drivers-installation-guide/main/nvidia.hook
    #sudo mkdir -p /etc/pacman.d/hooks
    #sudo mv ./nvidia.hook /etc/pacman.d/hooks/
fi

source source/install/install-yay

# Start the bluetooth service
# echo -e "Starting the Bluetooth Service...\n"
# sudo systemctl enable --now bluetooth.service
# sleep 2