#!/bin/bash

RED='\033[0;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color

displayHelp() {
  printf "Usage: hyprland [OPTIONS]\n"
  printf "Options:\n"
  printf "  -h                        show help text\n"
  printf "  --no-install              If not needed to install hyprland packages\n"
}

while getopts ":h" opt; do
  case $opt in
  h)
    displayHelp
    exit 0
    ;;
  esac
done

to_install=true

# Цикл для обработки всех аргументов
while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
  --no-install)
    to_install=false
    ;;
  *)
    # Обработка неизвестных аргументов
    echo "Неизвестный аргумент: $1"
    ;;
  esac
  shift
done

### Install packages ####
if [[ $to_install == true ]]; then

  source source/install/install-yay
  sudo pacman -S --noconfirm inotify-tools libnotify

  sudo pacman -S --noconfirm sddm foot hyprland otf-font-awesome ttf-jetbrains-mono \
    hyprpaper xdg-desktop-portal-hyprland qt6-wayland \
    dunst dolphin wofi
  yay -S --noconfirm rustup gtk-layer-shell eww

  # Clean out other portals
  yay -R --noconfirm xdg-desktop-portal-gnome xdg-desktop-portal-gtk

  #sudo sh install/eww/install-rust
  #sh install/eww/install-eww
fi

sudo systemctl enable sddm

source source/export-envs
echo -e "${GREEN}==>${WHITE} hypr config home = $HYPR_CONFIG_HOME${NC}"

mkdir -p $HYPR_CONFIG_HOME
yes | cp -Rf config/* $HYPR_CONFIG_HOME/
yes | cp -Rf resources/wallpaper.png $HYPR_CONFIG_HOME/hypr

chmod +x $HYPR_CONFIG_HOME/hypr/launch-hyprland
chmod +x $HYPR_CONFIG_HOME/waybar/launch-waybar
chmod +x $HYPR_CONFIG_HOME/eww/launch-eww
chmod +x $HYPR_CONFIG_HOME/hypr/bin/generate-hyprpaper

sudo sed -i "s|^Exec=.*|Exec=$HYPR_CONFIG_HOME/hypr/launch-hyprland|g" /usr/share/wayland-sessions/hyprland.desktop

### Script is done ###
echo -e "${GREEN}==>${WHITE} Script had completed. Now you can reboot to apply all settings${NC}"
