#!/bin/bash


displayHelp() {
  printf "Usage: hyprland [OPTIONS]\n"
  printf "Options:\n"
  printf "  -h                        show help text\n"
  printf "  --no-install              If not needed to install hyprland packages\n"
}

while getopts ":h" opt; do
  case $opt in
  h)
    displayHelp
    exit 0
    ;;
  esac
done

to_install=true

# Цикл для обработки всех аргументов
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        --no-install)
            to_install=false
            ;;
        *)
            # Обработка неизвестных аргументов
            echo "Неизвестный аргумент: $1"
            ;;
    esac
    shift
done

### Install packages ####
if [[ $to_install == true ]]; then
    sudo pacman -Syu --noconfirm

    read -rep 'Did you use desktop hyprland profile in archinstall? (y,n) ' HYP
    if [[ $HYP == "Y" || $HYP == "y" ]]; then
        sudo pacman -S --noconfirm foot weston waybar
    else
        yay -S --noconfirm hyprland kitty waybar \
        swaybg swaylock-effects wofi wlogout mako thunar \
        ttf-jetbrains-mono-nerd noto-fonts-emoji \
        polkit-gnome python-requests starship \
        swappy grim slurp pamixer brightnessctl gvfs \
        bluez bluez-utils lxappearance xfce4-settings \
        dracula-gtk-theme dracula-icons-git xdg-desktop-portal-hyprland

        # Clean out other portals
        echo -e "Cleaning out conflicting xdg portals...\n"
        yay -R --noconfirm xdg-desktop-portal-gnome xdg-desktop-portal-gtk
    fi
fi

mkdir -p ~/.config/
cp -R config/kitty ~/.config/
cp -R config/hypr ~/.config/

sudo mkdir -p /etc/sddm.conf.d

sudo cp -R source/startWeston.sh /etc/sddm.conf.d/
sudo cp -R source/startHyprland.sh /usr/share/wayland-sessions/

sudo chmod +x /etc/sddm.conf.d/startWeston.sh
sudo chmod +x /usr/share/wayland-sessions/startHyprland.sh

sudo cp /usr/lib/sddm/sddm.conf.d/default.conf /etc/sddm.conf.d
sudo sed -i 's/^DisplayServer=.*/DisplayServer=wayland/g' /etc/sddm.conf.d/default.conf
sudo sed -i 's/^CompositorCommand=.*/CompositorCommand=\/etc\/sddm.conf.d\/startWeston.sh/g' /etc/sddm.conf.d/default.conf
sudo sed -i 's/^Name=Hyprland/Name=Hyprland Wayland/g' /usr/share/wayland-sessions/hyprland.desktop
sudo sed -i 's/^Exec=Hyprland/Exec=\/usr\/share\/wayland-sessions\/startHyprland.sh/g' /usr/share/wayland-sessions/hyprland.desktop
sudo rm /usr/share/wayland-sessions/weston.desktop

### Script is done ###
echo -e "Script had completed. Now you can reboot to apply all settings\n"
