#!/bin/bash

arr=($(find config -type f))
arr2=($(find source -type f))

CONFIG_FILES=""
for f in "${arr[@]}"; do
    #echo $f
    CONFIG_FILES+="$f "
done

#echo $CONFIG_FILES

to_copy=true

# Цикл для обработки всех аргументов
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
    --no-copy)
        to_copy=false
        ;;
    *)
        # Обработка неизвестных аргументов
        echo "Неизвестный аргумент: $1"
        ;;
    esac
    shift
done

do_share() {
    for f in "${arr[@]}"; do
      if [[ $f != *"node_modules"* && $f != *"/types/"* && $f != *".ts" ]]; then
        sed -i 's/\r$//' "$f"
      fi
    done
    for f in "${arr2[@]}"; do
      sed -i 's/\r$//' "$f"
    done

    sed -i 's/\r$//' "install.sh"
    sed -i 's/\r$//' "after_install.sh"
    sed -i 's/\r$//' "source/hyprland"

    if [[ $to_copy == true ]]; then
        rsync -avh --exclude='ags/ts/node_modules' --exclude='ags/ts/types' config/ ~/.config

        rm -f ~/.config/hypr/wallpaper.png
        cp -Rf resources/wallpaper.png ~/.config/hypr

        chmod +x ~/.config/hypr/launch-hyprland
        chmod +x ~/.config/waybar/launch-waybar
        chmod +x ~/.config/hypr/launch-hyprpaper
        chmod +x ~/.config/hypr/bin/generate-hyprpaper
    fi
}

#while true; do
#    do_share &
#    inotifywait -e create,modify $CONFIG_FILES
do_share
#done
