#!/bin/bash

# It is normal that will be errors while installation. After reboot it will be gone

RED='\033[0;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color

sudo pacman -S --noconfirm zsh

CUR_PWD=$(pwd)
#cd $HOME/.cache
mkdir -p /tmp/oh-my-zsh
cd /tmp/oh-my-zsh || exit

echo -e "${GREEN}==>${WHITE} Install oh my zsh${NC}"
curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh

rm -f $HOME/.zshrc
cp $CUR_PWD/source/zsh/.zshrc $HOME
# sudo chown -R "$USER":"$USER" $HOME/.zshrc

new_variables=$(cat $CUR_PWD/resources/envs.env) # | envsubst)

export new_variables
perl -0777 -i -pe 's/(# ENV_VARIABLES\n).*?(# END_ENV_VARIABLES)/$1$ENV{new_variables}\n$2/s' \
    $HOME/.zshrc

# while read line; do
#     variable=$(echo "$line" | cut -d= -f1)
#     if ! grep -q "^$variable=" $HOME/.zshrc; then
#         echo "$line" | envsubst | tee -a $HOME/.zshrc
#     fi
# done < "$PWD/resources/envs.env"

source $HOME/.zshrc

IS_SUG=$ZSH/custom/plugins/zsh-autosuggestions
if [ ! -d "$IS_SUG" ]; then
    git clone https://github.com/zsh-users/zsh-autosuggestions.git $ZSH/custom/plugins/zsh-autosuggestions
else
    cd $ZSH/custom/plugins/zsh-autosuggestions || exit
    git pull
fi

IS_SYN=$ZSH/custom/plugins/zsh-syntax-highlighting
if [ ! -d "$IS_SYN" ]; then
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH/custom/plugins/zsh-syntax-highlighting
else
    cd $ZSH/custom/plugins/zsh-syntax-highlighting || exit
    git pull
fi

# change dafault shell
if [[ $SHELL != "/usr/bin/zsh" ]]; then
    echo -e "${GREEN}==>${WHITE} Change shell to zsh${NC}"
    chsh -s /usr/bin/zsh
fi

cd $CUR_PWD