#!/bin/bash

#CONFIG_FILES="$(find "$CONFIG_HOME"/ags/ts/src -type f)"

#trap "ags -q" EXIT
#
#while true; do
#    ags &
#    inotifywait -e create,modify "$CONFIG_FILES"
#    ags -q
#done
ags -q
ags &