#!/bin/bash
 
# export XDG_CURRENT_DESKTOP=Hyprland
# export XDG_SESSION_DESKTOP=Hyprland
# export XDG_SESSION_TYPE=wayland
# export EWW=/usr/bin/eww/./eww
# export WLR_NO_HARDWARE_CURSORS=1
# export WLR_RENDERER_ALLOW_SOFTWARE=1
export PATH=$PATH:$HOME/.bun/bin

exec Hyprland