#! /bin/bash

curl -fsSL https://bun.sh/install | sh

# Upgrade
# To upgrade to the latest version of Bun, run:

# bun upgrade

# If you need to remove Bun from your system, use the following commands.

# $ rm -rf ~/.bun # for macOS, Linux, and WSL