#!/bin/bash

#### Check for yay ####
ISYAY=/sbin/yay
if [ ! -f "$ISYAY" ]; then
    read -p "$(echo -e ${WHITE}"Would you like to install yay? (y,n) ${NC}")" HYP
    if [[ $YAY == "Y" || $YAY == "y" ]]; then
        CUR_PWD=$(pwd)
        cd /opt/ || exit
        sudo git clone https://aur.archlinux.org/yay.git
        sudo chown -R "$USER":"$USER" yay/
        cd /opt/yay/ || exit
        makepkg -si --noconfirm
        echo -e "yay was installed\n"
        cd $CUR_PWD
        
        echo -e "update yay\n"
        yay -Suy --noconfirm
    fi  
else
    echo -e "update yay\n"
    yay -Suy --noconfirm
fi