#!/bin/bash

#### Check for yay ####
ISYAY=/sbin/yay
if [ -f "$ISYAY" ]; then
else
    read -rep "yay was not located. Would you like to install it? (y,n) " YAY
    if [[ $YAY == "Y" || $YAY == "y" ]]; then
        CUR_PWD=$(pwd)
        cd /opt/ || exit
        sudo git clone https://aur.archlinux.org/yay.git
        sudo chown -R "$USER":"$USER" yay/
        cd /opt/yay/ || exit
        makepkg -si --noconfirm
        echo -e "yay was installed\n"
        cd $CUR_PWD
    else
        exit
    fi
fi

echo -e "update yay\n"
yay -Suy --noconfirm