#!/bin/bash

# script need excute with sudo
# uninstall - rustup self uninstall

RED='\033[0;31m'
YELLOW='\033[1;33m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color

echo -e "${RED}==>${WHITE} Now will be installed rustup and cargo for eww${NC}"

export RUSTUP_HOME=/usr/bin/rustup
export CARGO_HOME=/usr/bin/cargo

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

echo -e "${YELLOW}==>${WHITE} rustup and cargo installed${NC}"