#!/bin/bash

while read line; do
    variable=$(echo "$line" | cut -d= -f1)
    if ! grep -q "^$variable=" ~/.bashrc; then
        echo "$line" | envsubst | tee -a ~/.bashrc
    fi
done < "$(pwd)/resources/envs.env"

source ~/.bashrc