#!/bin/bash

RED='\033[0;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color

source resources/envs.env

#sudo pacman -S --noconfirm plasma-desktop kate kscreen konsole sddm dolphin jq discover \
#  plasma-nm plasma-pa bluez-qt kdeconnect

sudo pacman -S --noconfirm sddm jq python plasma-meta konsole dolphin kate qt5-tools

# for konsave
#sudo pacman -S --noconfirm python-pipx
#pipx install konsave
#pipx ensurepath

sudo systemctl enable sddm


