#!/bin/bash

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	eww daemon
	sleep 1
fi

width=$(sh config/eww/bin/get_resolution 0 40 --horizontal)

eww open bar --arg width="$width"px
eww open dock